### ISSUE TITLE
Cannot log into app.octoblu.com using my google account

### ISSUE THREAD

**Issue by shashiu** [octoblu/issues#56]
When I log into Octoblu using my google account, I now get the following error (used to work fine before)
Error: not connected
at MeshbluDb.insert (/srv/www/google_oauth/releases/20150518210144/node_modules/meshblu-db/src/meshblu-db.coffee:34:34)
at MeshbluDb.insert (/srv/www/google_oauth/releases/20150518210144/node_modules/meshblu-db/src/meshblu-db.coffee:1:1)
at /srv/www/google_oauth/releases/20150518210144/node_modules/meshblu-authenticator-core/src/device-authenticator.coffee:75:18
at /srv/www/google_oauth/releases/20150518210144/node_modules/meshblu-authenticator-core/src/device-authenticator.coffee:56:7
at /srv/www/google_oauth/releases/20150518210144/node_modules/meshblu-db/src/meshblu-db.coffee:22:38
at [object Object]._onTimeout (/srv/www/google_oauth/releases/20150518210144/node_modules/lodash/index.js:1839:43)
at Timer.listOnTimeout [as ontimeout](timers.js:112:15)

**Comment by AlisamfP** [comment]
I'm pretty sure this is related to the downtime we were experiencing yesterday. I'm seeing this with Facebook and Twitter as well. We're working on a fix right now.

**Comment by AlisamfP** [comment]
Google log in should be fixed now.
